### ISSUE TITLE
Invalid assembly generated in delayMicroseconds for teensy lc

### ISSUE THREAD

**Issue by expipiplus1** [PaulStoffregen/cores#102]
The instruction `sub %0, #1` is not legal on armv6 unless the register is `SP`

`subs` has to be used instead it seems: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0432c/CHDCICDF.html

**Comment by PaulStoffregen** [comment]
Please provide a program which I can copy into Arduino and compile to see & reproduce the error.

**Comment by PaulStoffregen** [comment]
Maybe you're using a different toolchain?

I can't reproduce this problem when building in Arduino/Teensyduino.

**Comment by expipiplus1** [comment]
Thanks! Sorry for never responding :/
