### ISSUE TITLE
USB Raw HID - NUM_ENDPOINTS

### ISSUE THREAD

**Issue by macaba** [PaulStoffregen/cores#108]
Apologies for the excessive upper casing in the issue title.

I'm in the process of trying to define a new USB Raw HID type with no SEREMU interface and I noticed the number of endpoints for USB_RAWHID is set to 6 where only 4 appear to be used. Is this an issue?

https://github.com/PaulStoffregen/cores/blob/d1a6e77ad949ef45ec79a25f49011ccdb85cd117/teensy3/usb_desc.h#L255

**Comment by PaulStoffregen** [comment]
Thanks
