### ISSUE TITLE
Porting advancetouchsensing to teensy3.x

### ISSUE THREAD

**Issue by shirish47** [PaulStoffregen/cores#113]
https://github.com/shirish47/AdvancedTouchSensing
 this can be an awesome idea to port this library to Teensy 3.1 with part of comparision being done in teensy3.x and not on processing.. I think this is possible as T3.x is fast and 32bit .. also it has a good sinwave generator using DAC. can someone suggest on this?

**Comment by PaulStoffregen** [comment]
Please post here:
https://forum.pjrc.com/forums/4-Suggestions-amp-Bug-Reports

This issue tracker is not the place to request porting libraries.
