### ISSUE TITLE
kinetis.h K66 RNG registers are wrong

### ISSUE THREAD

**Issue by manitou48** [PaulStoffregen/cores#136]
problem and fix described at 
https://forum.pjrc.com/threads/34808-K66-Beta-Test?p=107134&viewfull=1#post107134

**Comment by PaulStoffregen** [comment]
fixed.   thanks!
https://github.com/PaulStoffregen/cores/commit/663d7eaa7b7ebf98771707d8ac4f6a7ef7d95af2
