### ISSUE TITLE
Teensy 3.5/3.6 difference found in A10 & A11 pin mapping

### ISSUE THREAD

**Issue by soundanalogous** [PaulStoffregen/cores#184]
When working on adding Teensy 3.5 and 3.6 to Firmata Boards.h I found that in pins_arduino.h, [A10 and A11 are mapped to D64 and D65](https://github.com/PaulStoffregen/cores/blob/master/teensy3/pins_arduino.h#L101-L102), but in core_pins.h it appears that [A10 and A11 are mapped to D40 and D41](https://github.com/PaulStoffregen/cores/blob/master/teensy3/core_pins.h#L1270-L1271).

Not sure if this is an issue, but highlighting it just in case.

**Comment by PaulStoffregen** [comment]
Fixed.  Thanks.

**Comment by PaulStoffregen** [comment]
https://github.com/PaulStoffregen/cores/commit/52697d0ef6e44d8d1bc7fbc5e775b3f10f8524c9
