### ISSUE TITLE
MIDI device name can only be set once

### ISSUE THREAD

**Issue by alex-Arc** [PaulStoffregen/cores#218]
i have tested it on a T-LC and T3.2
i can only set the midi device name once.
compiling and uploading a new one even after restarting Arduino and the teensy loader results in the same name.

```
#include "usb_names.h"

// Edit these lines to create your own name.  The length must
// match the number of characters in your custom name.

#define MIDI_NAME   {'M','u','t','e'}
#define MIDI_NAME_LEN  4

// Do not change this part.  This exact format is required by USB.

struct usb_string_descriptor_struct usb_string_product_name = {
        2 + MIDI_NAME_LEN * 2,
        3,
        MIDI_NAME
};
```

**Comment by Theremingenieur** [comment]
Depends on the OS. Some cache the device name, so that further changes aren’t displayed correctly. After changing the name again, plug the Teensy on a fresh computer and you’ll see the new name.

**Comment by PaulStoffregen** [comment]
This example and the website have been updated with improved instructions.

Numerous people have confirmed this works.  I'm closing this old issue.
