### ISSUE TITLE
USB_SERIAL in Makefile does not work

### ISSUE THREAD

**Issue by PeterMitrano** [PaulStoffregen/cores#227]
I am trying to compile a simple serial 'hello world' program using the Makefile in this project (`teensy3/Makefile`), but the serial mode seems to be set to disabled. I can clearly see `-DUSB_SERIAL` being used to compile, and yet it doesn't work. I can build and upload and control LEDs etc, but serial does not work (no device appears under `/dev`).

**Comment by Theremingenieur** [comment]
On Linux? Did you install the Teensy udev rules from the PJRC.com website?

**Comment by PaulStoffregen** [comment]
Closing this one.  Github issues aren't the place for support questions.
