### ISSUE TITLE
Error oploading code to teensy

### ISSUE THREAD

**Issue by smarakini** [PaulStoffregen/cores#229]
Arduino: 1.8.1 (Windows 7), TD: 1.35, Board: "Teensy++ 2.0, Serial, 16 MHz, US English"

C:\Users\Sumanth\Documents\Arduino\libraries\usb_mouse\example.c:76:16: error: variable 'circle' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 int8_t PROGMEM circle[] = {

                ^

Error compiling for board Teensy++ 2.0.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Please help.

**Comment by PaulStoffregen** [comment]
Github is the wrong place for programming questions.

Ask your question here:
https://forum.pjrc.com/forums/3-Technical-Support-amp-Questions
