### ISSUE TITLE
PINC emulation refer to the same ports as PINB emulation so using PINC affects the wrong ports.

### ISSUE THREAD

**Issue by alpage-ca** [PaulStoffregen/cores#231]
Both PINBemulation and PINCemulation classes refer to the same ports (see below) but I believe that PINCemulation should be ports 14 through 19 unless I completely misunderstanding how it works.
(From avr_emulation.h)

inline int operator & (int val) const __attribute__((always_inline)) {
int ret = 0;
if ((val & (1<<0)) && digitalReadFast(8)) ret |= (1<<0);
if ((val & (1<<1)) && digitalReadFast(9)) ret |= (1<<1);
if ((val & (1<<2)) && digitalReadFast(10)) ret |= (1<<2);
if ((val & (1<<3)) && digitalReadFast(11)) ret |= (1<<3);
if ((val & (1<<4)) && digitalReadFast(12)) ret |= (1<<4);
if ((val & (1<<5)) && digitalReadFast(13)) ret |= (1<<5);
return ret;
}

**Comment by PaulStoffregen** [comment]
Thanks!  :)
