### ISSUE TITLE
encrypt audio ---->decrypt audio

### ISSUE THREAD

**Issue by yhyamak** [PaulStoffregen/cores#233]
I wounder if i can encrypt audio with AES or any other algorithm and send encrypted data through audio jack 
then receive  this data with another teensy and decrypt it 
if this possible can you post the code

**Comment by yhyamak** [comment]
Can i know the reason for clossing issue

**Comment by NicoHood** [comment]
This is not a forum, its an issue tracker. and this is not an issue. use the arduino forums for that. also it is up to you what you do with this lib
