### ISSUE TITLE
#define KEY_MEDIA_RANDOM_PLAY is wrong

### ISSUE THREAD

**Issue by benjaminaigner** [PaulStoffregen/cores#265]
This keycode is defined as following:

#define KEY_MEDIA_RANDOM_PLAY   ( 0xB0 | 0xE400 )

actually, this is the same value as "KEY_MEDIA_PLAY".
According to other sources, the value should be defined as:

#define KEY_MEDIA_RANDOM_PLAY   ( 0xB9 | 0xE400 )

Anyway, @PaulStoffregen keep up your nice work!

**Comment by PaulStoffregen** [comment]
Fixed.  Thanks!
