### ISSUE TITLE
DMAChannel.h - transferSize() for KINETISL doesn't set DMA_DCR_SSIZE bits properly

### ISSUE THREAD

**Issue by embedded-creations** [PaulStoffregen/cores#266]
```
			CFG->DCR = dcr | DMA_DCR_DSIZE(0) | DMA_DCR_DSIZE(0);
```
The code should clear both SSIZE and DSIZE bits, but it only clears SSIZE.  Sorry I don't have time to make a proper test case, but it should be easy to see there's a problem here.

**Comment by embedded-creations** [comment]
I still think there's something wrong here, but I completely missed the mask two lines above, so I'm going to step away from the computer and report it again if I see the issue.

**Comment by embedded-creations** [comment]
Indeed there is an issue, SSIZE isn't set, should be
```
CFG->DCR = dcr | DMA_DCR_SSIZE(0) | DMA_DCR_DSIZE(0);
```

**Comment by PaulStoffregen** [comment]
Thanks!
