### ISSUE TITLE
IPAddress.h should also define operator!=()

### ISSUE THREAD

**Issue by ssilverman** [PaulStoffregen/cores#270]
It is my understanding that if operator== is defined, then operator!= must be also.

**Comment by PaulStoffregen** [comment]
IPAddress.h is for compatibility with Arduino.  They don't have this in their IPAddress.h.

**Comment by ssilverman** [comment]
<frown>
So this means, in theory, that when comparing two IPAddresses, !(a == b) must be used instead of (a != b)? At least that’s what I’m getting out of this. Yikes. I’ll go file a bug report with them.

**Comment by PaulStoffregen** [comment]
Yes, please ask Arduino to fix this in their IPAddress.h.  Then I will adopt whatever fix they choose.

I hope you can understand why I'm reluctant to allow this sort of compatibility code to diverge from Arduino's version.

**Comment by ssilverman** [comment]
Completely. Lots of Arduino code out there you’d want to be compatible.

**Comment by ssilverman** [comment]
I hit ‘Close’ by mistake. I’ll go file this with them and update here...

**Comment by ssilverman** [comment]
I just submitted https://github.com/arduino/Arduino/issues/7336.

**Comment by ssilverman** [comment]
Looks like they changed it. :)

**Comment by ssilverman** [comment]
For posterity, here's where they changed it: https://github.com/arduino/ArduinoCore-API/commit/d5ae3faba1d69500f920c57b2afac59021831278
(Issue https://github.com/arduino/Arduino/issues/7336)
