### ISSUE TITLE
Publish teensyduino 1.42 on Github Releases

### ISSUE THREAD

**Issue by tyler-sommer** [PaulStoffregen/cores#282]
Hi there!

I did not know that teensyduino 1.42 was released until I happened to see it mentioned on another medium. I may be the only one to make this mistake, but the release is not listed on the GitHub Releases page: github.com/PaulStoffregen/cores/releases -- could you kindly publish the 1.42 release on Github?

Very much appreciated!

**Comment by PaulStoffregen** [comment]
It's too late now for a 1.42 tag.

Announcements are done on the forum.  If you want to be notified, this is how:

![forum_subscribe](https://user-images.githubusercontent.com/965463/44945616-17c69e80-ada2-11e8-86e8-8429c4510891.png)

**Comment by tyler-sommer** [comment]
No worries, thanks for the pointer. And thanks for Teensy!
