### ISSUE TITLE
Tag Older Release Commits

### ISSUE THREAD

**Issue by dmadison** [PaulStoffregen/cores#284]
I recently updated an older project to work with more recent Teensy versions, and it would be great if the `cores` commits were tagged at each version release. There are a couple tagged already, but quite a few are missing.

The project I was updating was based on version 1.21, so I only tracked the updates from then until now. I installed each Teensyduino version into a new Arduino installation, then compared the files with git. Here are the missing tags and their corresponding commits to the best of my knowledge:

| Version # | Commit | Date |
|-----------|--------|-----------|
| 1.21 | [6ed0c5f](../commit/6ed0c5f) | 3/15/2015 |
| 1.22 | [0dcc3a1](../commit/0dcc3a1) | 4/4/2015 |
| 1.23 | [66b28af](../commit/66b28af) | 5/13/2015 |
| 1.24 | [4cf71a4](../commit/4cf71a4) | 6/23/2015 |
| 1.25 | [c0196ca](../commit/c0196ca) | 9/18/2015 
| 1.26 | [c006772](../commit/c006772) | 11/11/2015 |
| 1.28 | [8a7f15d](../commit/8a7f15d) | 4/10/2016 |
| 1.32 | [9c88ebe](../commit/9c88ebe) | 12/9/2016 |
| 1.33 | [2b24e39](../commit/2b24e39) | 12/14/2016 |
| 1.34 | [8a02ea6](../commit/8a02ea6) | 12/27/2016 |
| 1.36 | [2852a52](../commit/2852a52) | 3/31/2017 |
| 1.37 | [7099935](../commit/7099935) | 6/19/2017 |
| 1.38 | [a8ed957](../commit/a8ed957) | 8/28/2017 |
| 1.39 | [dba7390](../commit/dba7390) | 9/6/2017 |
| 1.4 | [3ede33c](../commit/3ede33c) | 10/10/2017 |
| 1.42 | [9b5d9f9](../commit/9b5d9f9) | 6/7/2018 |

(Note the dates are the version releases, not the dates for the commits themselves.)

I only have a cursory knowledge of git tags, but I think it should be possible to back-tag the older commit locally and then push to the repo. Although sadly I don't believe it's possible to add them to a pull request otherwise I would.

I know you're busy and this is probably the lowest possible priority on your to-do list, but I'm sure others would find it useful. In the meantime I'm sure the list above would suffice.

**Comment by PaulStoffregen** [comment]
I also don't know how to do this with git / github.

**Comment by dhylands** [comment]
This stackoverflow article describes how to create tags using git and then push them to github:
https://stackoverflow.com/questions/18216991/create-a-tag-in-github-repository

**Comment by Lauszus** [comment]
@PaulStoffregen here is a bash script for creating all the missing tags and pushing them:

```bash
commits=("6ed0c5f" "0dcc3a1" "66b28af" "4cf71a4" "c0196ca" "c006772" "8a7f15d" "9c88ebe" "2b24e39" "8a02ea6" "2852a52" "7099935" "a8ed957" "dba7390" "3ede33c" "9b5d9f9")
tags=("1.21" "1.22" "1.23" "1.24" "1.25" "1.26" "1.28" "1.32" "1.33" "1.34" "1.36" "1.37" "1.38" "1.39" "1.40" "1.42")

for i in ${!commits[*]}; do
	git checkout "${commits[$i]}"
	GIT_COMMITTER_DATE="$(git show --format=%aD | head -1)" git tag -a "${tags[$i]}" -m "${tags[$i]}"
done

git checkout master
git push --tags origin master
```

**Comment by PaulStoffregen** [comment]
Ok, done.  How's it look?

**Comment by Lauszus** [comment]
@PaulStoffregen looks good to me: https://github.com/PaulStoffregen/cores/tags :)

**Comment by PaulStoffregen** [comment]
ok, closing this issue

**Comment by dmadison** [comment]
Fantastic! Thanks everyone.
