### ISSUE TITLE
USB Descriptor String Descriptor Issue

### ISSUE THREAD

**Issue by false** [PaulStoffregen/cores#286]
Hi,

There may be an issue with the string descriptor information sent on the usb setup.
I tried to debug it but didn't figure out how the missing data should be sent.

Here is the problem : 
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  
0x01   0x0000  "Manufacturer"
0x02   0x0000  "Product name"

And it should be : 

Index  LANGID  String
0x00   0x0000  0x0409 
0x01   0x0409  "Manufacturer"
0x02   0x0409  "Product name"

So first missing part is the wLangID not being set.
And the second missing part is the LangID field not being set.
(
{0x0300, 0x0000, (const uint8_t *)&string0, 0},
        {0x0301, 0x0409, (const uint8_t *)&usb_string_manufacturer_name, 0},
        {0x0302, 0x0409, (const uint8_t *)&usb_string_product_name, 0},
        {0x0303, 0x0409, (const uint8_t *)&usb_string_serial_number, 0},
)

**Comment by PaulStoffregen** [comment]
Let's use the forum.  Please do not duplicate post.

https://forum.pjrc.com/threads/54009-USB-Descriptor-String-Descriptor-Issue
