### ISSUE TITLE
need more weak symbols

### ISSUE THREAD

**Issue by xxxajk** [PaulStoffregen/cores#34]
pins_teensy.c
`port[abcde]_isr` should be prefixed with `__attribute__((weak))`
so that it can be overridden with other libraries/code in order to do groups of pins on an ISR together.
As an example, if I want to monitor port D bits 0, 1, 2, and 3 for a pin change, but don't care WHICH one changed, I can write code to do that, and output the entire nybble. This allows for the ability to do parallel signal analysis, much like a logic analyzer... which is exactly what I need to do.
There are possibly other use cases as well, such as monitoring a bit stream inputs for a bit-banged slave-mode SPI implementation.
I can think of many other uses as well, too numerous to list here.

**Comment by PaulStoffregen** [comment]
attachInterruptVector() is meant to allow overriding hardware interrupts
