### ISSUE TITLE
Should LPUARTx_BAUD_BOTHEDGE be set when OSR is in the range 4-7?

### ISSUE THREAD

**Issue by ssilverman** [PaulStoffregen/cores#405]
Should LPUARTx_BAUD_BOTHEDGE be set when OSR is between 4-7? The IMXRT1060RM_rev1.pdf spec mentions this (page 2987).

https://github.com/PaulStoffregen/cores/blob/73ea157600a7082686d9cc48786a73caa7567da9/teensy4/HardwareSerial.cpp#L147

**Comment by PaulStoffregen** [comment]
Yes.  I was able to reproduce the problem with this code, and pins 0-1 shorted.

```
void setup() {
  Serial1.begin(6000000);
}

void loop() {
  Serial1.write(0x5A);
  delayMicroseconds(1);
  if (Serial1.available()) {
    int c = Serial1.read();
    Serial.println(c, HEX);
  }
  delayMicroseconds(10);
}
```

fwiw, here's the waveform on those pins

![file](https://user-images.githubusercontent.com/965463/70794086-a79f1a80-1d51-11ea-93e6-af57bc91c0e0.png)
