### ISSUE TITLE
defines for Random Number Generator Accelerator on Teensy 4.0

### ISSUE THREAD

**Issue by phulst** [PaulStoffregen/cores#423]
It appears that the necessary definitions to use the RNGA on Teensy 4.0 are missing.  
I followed example code from

https://forum.pjrc.com/threads/48745-Teensy-3-6-Random-Number-Generator

but this doesn't compile for Teensy 4. I found that the defines for RNG_CR and SIM_SCGC6  are missing. These are present in the kinetis.h file for teensy3 but I found no such definitions for teensy4. 

Is there a different way to use RNGA on teensy4,  and if so, where can I find example code?

**Comment by phulst** [comment]
after digging  around  in the forums a bit more I did  come across some sample code  for the  T4. 

https://forum.pjrc.com/threads/54711-Teensy-4-0-First-Beta-Test?p=195000&viewfull=1#post195000

that will likely unblock me for now. However it would still be nice if the T4 TRNG registers could be included with the core libraries.  I would send you a pull request if I was more well-versed with this stuff and knew all the best practices for embedded C code...

**Comment by PaulStoffregen** [comment]
Fixed by https://github.com/PaulStoffregen/cores/commit/c9e3cc0daecddb3a28f28e7053db63f94ffd40dd

**Comment by PaulStoffregen** [comment]
If anyone finds this old issue, code was added to the Entropy library to provide TRNG access.
