### ISSUE TITLE
T4: WFI

### ISSUE THREAD

**Issue by FrankBoesing** [PaulStoffregen/cores#441]
void loop {
Serial.println("ZZzzzzz");
delay(1);
asm ("wfi");
Serial.println("Good Morning");
delay(100);
}
The systick should wake up the T4 - however the program stops after "ZZzzzz"

I guess the idle mode needs to be configured somehow.

**Comment by FrankBoesing** [comment]
Maybe this PDF is useful: https://www.nxp.com/docs/en/application-note/AN12085.pdf

**Comment by FrankBoesing** [comment]
Ok... WFI DOES wake the core :) It's just that it happens not in short intervals with systick (other than on T3.x)
If you send a text in SERMON , the T4 wakes up.

Ok, I can live with that. It's just different on the 3.x
Question is, wether this needs a fix or not... i don't know.

**Comment by Defragster** [comment]
I've seen inconsistent results from use of WFI on T_4.

If a Serial.print() is outbound it wakes?  If not it never wakes was the last I 'inferred' when I left that sketch.

There is an NXP_DOC that explains 'proper and complete use of WFI' on the IMXRT - I linked it during T4_Beta and got no mention.  It is an involved process it seems of setting things right to do WFI and then to return from WFI.

https://www.nxp.com/docs/en/application-note/AN12085.pdf

System Idle is the lowest 'idle' mode on WFI ...

![SystemIdle_WFI](https://user-images.githubusercontent.com/8165609/75767461-b9acab80-5cf7-11ea-89c4-595ce577b9c5.png)

**Comment by FrankBoesing** [comment]
For me, it'ok as it is. Better than on T3.x where systick wakes it.
Deeper sleeping can be handled by a library. 

Am 3. März 2020 11:37:41 MEZ schrieb Defragster <notifications@github.com>:
>I've seen inconsistent results from use of WFI on T_4.
>
>If a Serial.print() is outbound it wakes?  If not it never wakes was
>the last I 'inferred' when I left that sketch.
>
>There is an NXP_DOC that explains 'proper and complete use of WFI' on
>the IMXRT - I linked it during T4_Beta and got no mention.  It is an
>involved process it seems of setting things right to do WFI and then to
>return from WFI.
>
>https://www.nxp.com/docs/en/application-note/AN12085.pdf
>
>System Idle is the lowest 'idle' mode on WFI ...
>
>![SystemIdle_WFI](https://user-images.githubusercontent.com/8165609/75767461-b9acab80-5cf7-11ea-89c4-595ce577b9c5.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulStoffregen/cores/issues/441#issuecomment-593881846

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
