### ISSUE TITLE
SIM_SCGC6_FTM2 omitted?

### ISSUE THREAD

**Issue by truher** [PaulStoffregen/cores#482]
https://github.com/PaulStoffregen/cores/blob/d0d1177153af983a6fd5888e8660b0fae078297f/teensy3/kinetis.h#L1225

hey, is SIM_SCGC6_FTM2 omitted from kinetis.h on purpose?

**Comment by PaulStoffregen** [comment]
Yes, this is intentional.  The FTM2 enable is actually SIM_SCGC3_FTM2 on the Kinetis K chips.
