### ISSUE TITLE
Running DMA for UART in Teensy3.6

### ISSUE THREAD

**Issue by tahasadr** [PaulStoffregen/cores#493]
Hello.
I want to use DMA for receiving UART data. I searched for a code and found uartevent but it was for teensy3.1 which is not mine. is there any code for running DMA for receiving UART data? if not, is there any example for this DMAChannel.h code for me to know how to use it?
Thanks,

**Comment by PaulStoffregen** [comment]
This is the wrong place for questions.  Ask on the forum.
https://forum.pjrc.com/forums/2-Project-Guidance
