### ISSUE TITLE
Keycode question

### ISSUE THREAD

**Issue by bitboy85** [PaulStoffregen/cores#525]
I've had a look at the file https://github.com/PaulStoffregen/cores/blob/master/teensy/keylayouts.h where i found
`#define KEY_B                   (   5  | 0xF000 )`
according to the usb specs the keycode for 'B' is only 5. Is there a special reason why you translate it to 0xF005?
https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf, page 53

Or to get it the other way round: Does this library provide a function which allows to send a usb keycode?
Something like keyboard.WriteCode(5) => types 'b'

The reason behind is i want to manage different layouts somewhere else and thus want to pass only keycodes instead of char or string to the teensy.

**Comment by PaulStoffregen** [comment]
Please ask on the forum.  Github issues aren't the place for questions.
