### ISSUE TITLE
Teensy3 / Teensy4 Stream.timedRead() is private instead of protected

### ISSUE THREAD

**Issue by herrfrei** [PaulStoffregen/cores#531]
Issue #388 already described the problem, but I found the declaration if timedRead() as private and not protected as required. The ArduinoHttpClient library as well as khoih.prog/EthernetWebServer that is marked as compatible with Teensy use timedRead() in a  class derived from Client and hence the compiler produces an error.

Solution: declare timedRead() as protected.

**Comment by ssilverman** [comment]
This issue can be closed, as it was fixed in #619.
