### ISSUE TITLE
Missing ARDUINO_ARCH_{architecture} build parameter as described in the Arduino Platform Specification

### ISSUE THREAD

**Issue by lnlp** [PaulStoffregen/cores#560]
The [Arduino Platform Specification](https://arduino.github.io/arduino-cli/latest/platform-specification/) describes the `ARDUINO_ARCH_{build.arch}` architecture build parameter. This parameter is missing in the Teensy Arduino cores.

The architecture parameter is normally defined in `platform.txt`. The Teensy cores appear not to use `platform.txt` but that does not mean that the architecture parameter should not be passed to the build process.

The architecture parameter is essential for determining the used architecture in cross-platform applications, so the build process can be customized and adapt to needs of certain cores. All common Arduino cores define the architecture parameter (except for the Teensy cores).

The lack of definition of the architecture parameter in the Teensy cores prevents consistent checking of the architecture in cross platform applications.

Architecture parameters for the most common Arduino cores are:
ARDUINO_ARCH_AVR
ARDUINO_ARCH_SAMD
ARDUINO_ARCH_MBED
ARDUINO_ARCH_STM32
ARDUINO_ARCH_ESP32
ARDUINO_ARCH_ESP8266

**Please add the architecture build parameter to the Teensy cores to comply with the Arduino Platform Specification.**

It will take little efforts to implement.

_(The architecture build parameter could be looking something like `ARDUINO_ARCH_NXPKINETIS`, `ARDUINO_ARCH_KINETISL2`, or whatever)_

**Comment by PaulStoffregen** [comment]
No plans to do this.

**Comment by lnlp** [comment]
> No plans to do this.

For what reason?

**Comment by gpb01** [comment]
Mmm ... I suppose because it requires some not easy work ... have you seen the name of the folder where the "_cores_" for the teensy are located? Is "hardware/teensy/**avr**" and ... _build.arch_ i based "**_on the architecture folder of the hardware package_**" so, if the _build.arch_ parameter is added in platform.txt, you will receive the **AVR** architecture :-\

This means that the folders structure, within the hardware, folder should be rethought for the various possibilities ...

Just _my 2¢_ 

Guglielmo

**Comment by PaulStoffregen** [comment]
> so certain cross-platform applications

Can you be more specific about "certain"?

**Comment by lnlp** [comment]
> Can you be more specific about "certain"?

I mean _any_ applications that want to check the architecture build parameter. 
While it will be possible to check for other build flags to detect that code is compiled for Teensy, it's a pitty that the Teensy cores don't provide the standard ARDUINO_ARCH_ build parameter.
Standards and guidelines in general make compatibility, sharing and reuse of code simpler.
For a cross-platform application I was looking to fix a problem. I needed to check certain aspects of the Arduino cores for all supported boards. During the process I observed that the Teensy cores do not generate the ARDUINO_ARCH_ build parameter which made it less easy to make some comparisons.

**Comment by PaulStoffregen** [comment]
Again, *which* application?  Be specific.

**Comment by lnlp** [comment]
I'm not sure what is not clear about my post above.
For clarity I have added the word "may".

I can't name you a specific application at the moment.
As said, while investigating a problem I ran into I discovered that Teensy cores do not provide the ARDUINO_ARCH_ build parameter. That problem is not related to Teensy, but I made my observation while searching for the problem cause.

**Comment by FrankBoesing** [comment]
So, _are_ there any applications that do that?

**Comment by lnlp** [comment]
Teensy cores (currently) do not supply the standard ARDUINO_ARCH_xxx build parameter.
I have ran into this and have reported it. I have also motivated why it is better to provide it.
It will be up to you to do something with it or not.
I'm not sure why you keep asking for example applications. I cannot provide you the answer.
I have observed and reported the issue. There probably was reason to invest my time and efforts in reporting it. Whether something is done with it or not is totally up to you.

**Comment by PaulStoffregen** [comment]
The answer is still no, exactly the same as when I initially replied and closed this issue.

**Comment by lnlp** [comment]
"I have no plans to do that" without any further explanation feels somewhat like 'F... ..o!'.
That any (substantial) explanation is still lacking therefore doesn't surprise me at all.
I don't care you whether you implement it or not. I do care about substantive replies though.

**Comment by PaulStoffregen** [comment]
You are not owed any sort of explanation, especially not when you will not name even 1 application.

I'm going to ask you to please understand Robin & I are managing an extraordinarily difficult situation involving labor shortage due to pandemic social distancing requirements while struggling to maintain supplies in the midst of a global semiconductor shortage.  We are far behind on many important tasks.  Continuing to bring this up after a clear answer has been given is not helping.

Please, accept that the answer is no.

**Comment by lnlp** [comment]
I understand your situation.
Thanks for the heads up.
