### ISSUE TITLE
cmsis_gcc - why isn't the assembler version of pkhtb/pkhbt used?

### ISSUE THREAD

**Issue by FrankBoesing** [PaulStoffregen/cores#581]
https://github.com/PaulStoffregen/cores/blob/3b7ddbddd21665036200233c534bde49ee12566b/teensy4/cmsis_gcc.h#L2140

**Comment by PaulStoffregen** [comment]
The honest "why" is this file was just copied to allow a specific library to compile.  Library works = problem solved!

**Comment by FrankBoesing** [comment]
We both know that as it is there it will be used by other libraries / users :)  
I'll test it next weekend. If there is a problem, I'll report it. If not, too... ;)  
Audio uses pkhtp/pkhbt extensively in the asm copies, since years.

**Comment by FrankBoesing** [comment]
Ok... i know the reason.
They are just not the same.  In assembler the shift can't be a register (must be const).

The question remains, why the used these names - there is just no assembler equivalent. This is irritating and and poor solution.
But I think we can't do much about it.

Closing.

**Comment by PaulStoffregen** [comment]
> But I think we can't do much about it.

Maybe this will help, even if only slightly?
https://github.com/PaulStoffregen/cores/commit/b6cf473db50518e1af3951a1df44b05f0fb8c3fd
