### ISSUE TITLE
Teensy installer breaks Stino

### ISSUE THREAD

**Issue by bo01ean** [PaulStoffregen/cores#65]
Cross post from Stino issue. Not sure where the problem is:
https://github.com/Robot-Will/Stino/issues/252

Uninstalling Teensy libs for the time being.

**Comment by PaulStoffregen** [comment]
Which version of Arduino is this? When installing Teensyduino, did install some, all or none of the optional extra libraries?

These small details, not present in your message, matter greatly for resolving problems like this.

**Comment by PaulStoffregen** [comment]
I'm closing this issue, due to lack of info.
