### ISSUE TITLE
HardwareSerial availableforWrite() using RX head and tail

### ISSUE THREAD

**Issue by noisymime** [PaulStoffregen/cores#666]
Using a Teensy and getting a number of strange lockups when transmitting over hardware serial. The code relies heavily on monitoring the transmit buffer that is available as blocking is not desirable in this case. 

In trying to track down the lockup issue I came across this in the `Serial.availableForWrite()` function in `HardwareSerial.cpp`:

```
int HardwareSerial::availableForWrite(void)
{
	uint8_t head, tail;

	head = rx_buffer_head;
	tail = rx_buffer_tail;
	if (head >= tail) return TX_BUFFER_SIZE - 1 - head + tail;
	return tail - head - 1;
}
```

Shouldn't `head` and `tail` here be getting set to the `tx` variables rather than the `rx` ones?

**Comment by PaulStoffregen** [comment]
availableForWrite() returns the amount of data which can be transmitted without delay.

Documentation here: availableForWrite

**Comment by PaulStoffregen** [comment]
Yes, you're right.  I first looked at Teensy 4.0.  Then yes, seems this has been wrong on Teensy 2.0 for a very long time.  Should be fixed now (or next software release).
