### ISSUE TITLE
usbMidi.sendAfterTouchPoly seems to be a broken function

### ISSUE THREAD

**Issue by mikeisnottoast** [PaulStoffregen/cores#668]
Wanted to add some Poly Aftertouch to a midi controller I'm working on. As best I can tell, the function usbMIDI.sendAfterTouchPoly does not actually send any midi info over USB that I can detect in Max.

`
void setup() {
  Serial.begin(9600); 

}

void loop() {

usbMIDI.sendAfterTouchPoly(2, 100, 1);

   delay(100);
 
 
 

}`

TeensyLC

Teensyduino 1.8.19

**Comment by mikeisnottoast** [comment]
I was mistaken, Ableton Live does not support poly aftertouch, the function works as expected.

**Comment by insolace** [comment]
Hello Mike,This is probably outside the scope of teensy, but Ableton live 11 does support poly aftertouch if you configure your device as MPE in the midi preference tab.Cheers,Eric BatemanOn Dec 15, 2022, at 2:03 PM, mikeisnottoast ***@***.***> wrote:﻿
I was mistaken, Ableton Live does not support poly aftertouch, the function works as expected.

**Comment by PaulStoffregen** [comment]
Thanks for the followup.  I've only ever tested with simple utilities like MIDI-Ox on Windows or aseqdump on Linux.
