### ISSUE TITLE
Expose ` File`s `FileImpl`

### ISSUE THREAD

**Issue by pr8x** [PaulStoffregen/cores#670]
Would be nice to expose `File::f` (`FileImpl`) somehow. The [usb host library](https://github.com/PaulStoffregen/USBHost_t36) has `FsFile` which supports getting file attributes etc. and it's currently impossible to extract the file impl to access this useful info. Any plans to expose it?

**Comment by PaulStoffregen** [comment]
No, it's abstraction layer.  It's entire purpose is to not expose this sort of thing.

**Comment by pr8x** [comment]
How about exposing `isHidden()` on `File`? Not sure how feasible it is to require that interface for all file implementations (might not be supported for some file systems).
