### ISSUE TITLE
DMAChannel.h LC transferCount

### ISSUE THREAD

**Issue by manitou48** [PaulStoffregen/cores#69]
in the following thread
 https://forum.pjrc.com/threads/28439-Teensy-LC-Trying-to-Link-DMA-Channels
it suggests that shift to get byte-count in LC's transferCount() should be 
 CFG->DSR_BCR = len << n;

**Comment by PaulStoffregen** [comment]
Looks like this was fixed by https://github.com/PaulStoffregen/cores/pull/74
