### ISSUE TITLE
kinetis.h  TMPx_SC DMA flag not defined

### ISSUE THREAD

**Issue by manitou48** [PaulStoffregen/cores#70]
There is a DMA bit in the LC TPMx_SC that is not in the teensy 3 FTMx_SC and no corresponding symbol in kinetis.h 
   need FTM_SC_DMA as 0x100 

discussed in https://forum.pjrc.com/threads/28439-Teensy-LC-Trying-to-Link-DMA-Channels
and https://forum.pjrc.com/threads/27689-Teensy-LC-Beta-Testing?p=69176&viewfull=1#post69176

**Comment by PaulStoffregen** [comment]
closing this, it was added at some point.
