### ISSUE TITLE
minor documentation issue in eeprom.c; wrong serial flash commands mentioned in comment

### ISSUE THREAD

**Issue by fenrog** [PaulStoffregen/cores#727]
with respect to https://github.com/PaulStoffregen/cores/blob/master/teensy4/eeprom.c

line 326
`FLEXSPI_LUT60 = LUT0(CMD_SDR, PINS1, 0x52) | LUT1(ADDR_SDR, PINS1, 24); // 20 = sector erase`
should read as
`FLEXSPI_LUT60 = LUT0(CMD_SDR, PINS1, 0x52) | LUT1(ADDR_SDR, PINS1, 24); // 52 = 32kB block erase`

line 350
`FLEXSPI_LUT60 = LUT0(CMD_SDR, PINS1, 0xD8) | LUT1(ADDR_SDR, PINS1, 24); // 20 = sector erase`
should read as
`FLEXSPI_LUT60 = LUT0(CMD_SDR, PINS1, 0xD8) | LUT1(ADDR_SDR, PINS1, 24); // D8 = 64kB block erase`

**Comment by PaulStoffregen** [comment]
Updated.  Thanks.

https://github.com/PaulStoffregen/cores/commit/7435e4bbe96c0819dc28ea64bfe4f152f92a486e
