### ISSUE TITLE
Grave key

### ISSUE THREAD

**Issue by chuckb** [PaulStoffregen/cores#749]
Within the teensy 3 library (and maybe within others...I did not check), the key layout for the grave key is labeled `#define KEY_TILDE               (  53  | 0xF000 )`. Tilde is emitted with the shift modifier key, so I believe that the name is mis-labeled and should be KEY_GRAVE (or KEY_BACKTICK since some may not recognize the grave reference). I believe that all other key definitions are given with their non-shifted variants.

**Comment by PaulStoffregen** [comment]
Yes, it is inconsistent.  But not planning to change.
