### ISSUE TITLE
Empty interrupt.h in cores/teensy3/avr/interrupt.h

### ISSUE THREAD

**Issue by Flying-Bolt** [PaulStoffregen/cores#78]
The inertrupt.h file in Teensy Core Libraries for Arduino in cores/teensy3/avr/interrupt.h is empty

**Comment by FrankBoesing** [comment]
I think this is intentional.

**Comment by Flying-Bolt** [comment]
=:-|    ..mmh

**Comment by PaulStoffregen** [comment]
Yes, it is supposed to be empty.

The empty file allows libraries and sketches with #include <avr/interrupt.h> to compile.
