### ISSUE TITLE
PDB channel 1 for ADC1

### ISSUE THREAD

**Issue by pedvide** [PaulStoffregen/cores#80]
The definitions for the registers for the PDB channel 1 that controls the ADC1 are missing kinetis.h
They are given in this old forum post (https://forum.pjrc.com/threads/25153-PDB0CH1-register-definitions) and I have checked that at least PDB0_CH1C1 is correct.

**Comment by PaulStoffregen** [comment]
added
https://github.com/PaulStoffregen/cores/commit/0bdac50dcb8bf5cabecd2c268333582a36ca22a1
